---
minimum_pre_commit_version: 2.16.0
exclude: >
  (?x)^(
      .+/.venv/.+|.+/dist/.+|.+/.autovenv|.+/docs/|.github|marvel_api/mage_data/
  )$
fail_fast: true
default_language_version:
  python: python3
default_stages:
  - prepare-commit-msg
  - commit

repos:
  # Python: Black formatter
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--safe, --quiet, --config=./pyproject.toml]
        files: \.pyi?$
        exclude: .github/|.vscode/|marvel_api/mage_data/
        # override until resolved: https://github.com/psf/black/issues/402
        types: []

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.2
    hooks:
      - id: autoflake
        exclude: marvel_api/mage_data/
        args:
          - --in-place
          - --remove-all-unused-imports
          - --expand-star-imports
          - --remove-duplicate-keys
          - --remove-unused-variables

  # Flake8
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--config=.flake8", "marvel_api/"]
        # exclude: *fixtures
        exclude: scala|doc/|tests/|marvel_api/mage_data/
        additional_dependencies:
          # Finding likely bugs and design problems in your program.
          - flake8-bugbear
