FROM postgres:13-alpine3.17

LABEL author="Dênis Oliveira"
LABEL description="Postgres Image for Mage-AI marvel API"
LABEL version="1.0"

COPY /scripts/marvel_database.sql /docker-entrypoint-initdb.d/